### ISSUE TITLE
Create output folder automatically

### ISSUE THREAD

**Issue by OlegKunitsyn** [brunopacheco1/coboldoc#10]
Great job! Would be handy to get the structure of the documentation automatically.
* Create output directory if not exist.
* Create the index of the documentation files:
  - README.md for `md`
  - index.html for `html`

**Comment by brunopacheco1** [comment]
Hi Oleg, I just did the fixes as you suggested. I didn't have time to think about something sexier, let's say, so it is just a table of contents with links to the correct documentation files.
