### ISSUE TITLE
Parameters

### ISSUE THREAD

**Issue by spgennard** [brunopacheco1/coboldoc#12]
How do you say a parameter is by reference or by value?

**Comment by brunopacheco1** [comment]
Hey, thanks for opening this issue.

Well, it's a good question indeed. I am learning COBOL while coding this tool, so the short answer is: there is no way to differ that in COBOLDoc.

I just did quite fast research and it looks like you can define the parameter attribution when calling the function, but I am not sure if this is correct.

Could you show me how this is defined in the COBOL syntax? Then, this feature could be added.

**Comment by spgennard** [comment]
Micro Focus use *>> and standard xml documentation comments.

"Insert XML documentation comments - Visual Studio | Microsoft Docs" https://docs.microsoft.com/en-us/visualstudio/ide/reference/generate-xml-documentation-comments?view=vs-2019

**Comment by spgennard** [comment]
https://community.microfocus.com/t5/Visual-COBOL-Tips-Information/Generate-code-documentation-when-building-Visual-COBOL/ta-p/1741229

**Comment by brunopacheco1** [comment]
@spgennard I believe these comments are related to  #13, aren't they?

**Comment by brunopacheco1** [comment]
@spgennard I checked a bit more and it really looks like the way of passing a variable value into a procedure or a function depends on the calling program, not the other way around.

For me this is an interesting approach, but documentation-wise, I am not sure how to add this detail into the function/procedure/subprogram/module or even if it is really necessary.

What do you think?
