### ISSUE TITLE
vscode extension support (command line options)

### ISSUE THREAD

**Issue by spgennard** [brunopacheco1/coboldoc#14]
This is provided as a tool, could it be provided as a package so it can be used from a vscode extension (for example)

**Comment by brunopacheco1** [comment]
Sure, just let me know what you need.

**Comment by brunopacheco1** [comment]
Hi @spgennard . I already have an idea on how to split the CLI into a CLI and lib, I just need to understand what exactly you had in mind. What do you think it should be externalized as an API?

**Comment by brunopacheco1** [comment]
I believe, after adding Microfocus support, the API is going to be more mature, so I can expose it as an npm package.

**Comment by spgennard** [comment]
Micro Focus have adopted the Microsoft standard as used by C#, VB.net, F#.

Using this mechanism enables the developer to use standard tools such as sandcastle to generate and index code and in a mixed language solution the COBOL will be documented next to the other languages, which allows them to reference each other (links)

**Comment by spgennard** [comment]
I have just changed the title, as I think we don't need an api (but it would be nice).,

Having implemented the first part of the vscode extension, all I need to make it much nicer is:

- option to be "quieter" with the messages
- option to generate html to "stdout"
- option not to generate "index" html file

**Comment by brunopacheco1** [comment]
If you think an API is more appropriate, perhaps we should go for it. I just have to review the namespaces to something nicer and expose the typescript declarations.

**Comment by OlegKunitsyn** [comment]
I think we are stuck in 
https://github.com/spgennard/vscode_cobol/issues/189#issuecomment-683661014
