### ISSUE TITLE
Terminology: module

### ISSUE THREAD

**Issue by spgennard** [brunopacheco1/coboldoc#17]
The documentation generated groups items as "module" but COBOL does not have a concept of modules.

An operating system such as zOS has load modules, these are groups of objects, which may be COBOL programs other objects.

Linux/Windows has dynamic load libraries or shared objects, these contain a group of programs, classes, interface, valuetypes etc..

A program can have "sub-programs", entry-points

**Comment by OlegKunitsyn** [comment]
The term `COBOL module` is not declared in GnuCOBOL documentation, but widely used as a *Unit of Work* concept.
In the GnuCOBOL Programmer’s Guide, intrinsics e.g.:

> 6.16.50. MODULE-ID
> This function returmns the primary entry-point name i.e. the "PROGRAM-ID" or "FUNCTION-ID" of the program.

In the errors e.g.: 
> libcob: Cannot find module 'CBL_OC_DUMP'

In the FAQ at https://gnucobol.sourceforge.io/faq/index.html#call-static e.g.
> inform the compiler to link that call module statically

Don't want to trigger a holy-war here. For me, `COBOL module` is a COBOL entity with an entry-point that may have Linkage section. I guess, this sentence once added to GnuCOBOL documentation would be sufficient.

**Comment by spgennard** [comment]
I agree it's a not a holy-war issue, it is just that this way of talking COBOL programs is strange to me.

For me, a "module" is a group of programs, symbols, classes.  

The table of contents is the contents of the module but a program is defined as a module.

A module may contain only one program/entry symbol or class.

The MODULE-ID is the initial entry-point of the program.   This is not defined in source code but is defined by being the first source file on the "cobc" command line.

Other compiles such as Micro Focus, allow you to specify the initial entry-point (-e option).

My specific concerns are the use of "module" in the examples:

For example:

```*>*
*> The description of this module.
*>*
IDENTIFICATION DIVISION.
PROGRAM-ID. anymodule.
```

Should be:

```*>*
*> The description of this program.
*>*
IDENTIFICATION DIVISION.
PROGRAM-ID. literal.
```

The actual definition (from IBM) is:
```
Identification Division - Format

>>-+-IDENTIFICATION-+--DIVISION.
--PROGRAM-ID.------------------->
   |    (1)         |                           
   '-ID-------------'                           

>--+-program-name-+--------------------------------------------->
   |         (1)  |   
   '-literal------'  
```

**Comment by spgennard** [comment]
The GnuCOBOL also explains that a module is multple source files in a shared object/dll

```5.6 Does GnuCOBOL support modules?

Yes. Quite nicely in fact. Dynamically! COBOL modules, and object files of many other languages are linkable. As GnuCOBOL uses intermediate C, linkage to other languages is well supported across many platforms. The GnuCOBOL CALL instruction maps COBOL USAGE to many common C stack frame data representations.

Multipart, complex system development is well integrated in the GnuCOBOL model.

$ cobc -b hello.cob goodbye.cob
```

**Comment by brunopacheco1** [comment]
Well, I am back from my deserved holidays. Let's take part in this discussion. :)

I cannot call myself a COBOL developer, but perhaps I understood @spgennard point of view. 'Module' is an ambiguous word, so what we call module are actually programs (or subprograms), and **the module** is the entry-point of an executable or a dynamic lib, usually the first PROGRAM-ID in the first source file. Am I right @spgennard ?

In that case, perhaps the use of the word 'module' should be avoided, as the documentation file is scoped on a single source file. 
We may replace all 'module' by 'program'.  What do you say @OlegKunitsyn ?

**Comment by OlegKunitsyn** [comment]
Yes, please

**Comment by spgennard** [comment]
While we are talking about the scope, you might not be aware but COBOL some odd things:
 - A source file can include "many" programs, providing the scope of the program is complete (end program'ed)
 - COBOL programs can be nested and have visibility scopes through the use of global/common
   https://www.ibm.com/support/knowledgecenter/SS6SG3_6.1.0/pg/tasks/tpsubw06.html
 - COBOL programs can have extra entry-points with the same program
   https://www.ibm.com/support/knowledgecenter/en/SS6SG3_4.2.0/com.ibm.entcobol.doc_4.2/PGandLR/ref/rlpsentr.htm
   http://www.3kranger.com/HP3000/mpeix/doc3k/B3150090013.11820/169.htm
