### ISSUE TITLE
Template for the Documentation in HTML format

### ISSUE THREAD

**Issue by OlegKunitsyn** [brunopacheco1/coboldoc#3]
A user should be is able to choose the output format of the documentation.

**Comment by brunopacheco1** [comment]
I added an option and both MD and HTML will be supported.

**Comment by brunopacheco1** [comment]
@OlegKunitsyn I believe I reached a point where we should define a template for the documentation. If you have something in mind already, it may be helpful.

**Comment by OlegKunitsyn** [comment]
I found many repos like this for jsdoc
https://github.com/braintree/jsdoc-template/tree/master/tmpl

**Comment by brunopacheco1** [comment]
Thanks @OlegKunitsyn I just defined a template and definitely it can be improved in the future.
